server:
  port: 9001
spring:
  application:
    name: health
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/health?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
  redis:
    host: 192.168.137.129
    port: 6379
    password: root
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 1
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: isDeleted
      logic-delete-value: 0
      logic-not-delete-value: 1

health:
  imgPath: D:\JISHE\health\src\main\resources\static\img\
  videoPath: D:\JISHE\health\src\main\resources\static\video\
